### ISSUE TITLE
您好，在win10上使用idea编译Spring内存马模块，注入的时候报错：Agent JAR not found or no Agent-Class attribute

### ISSUE THREAD

**Issue by Dido1960** [ethushiroha/JavaAgentTools#2]
没有修改Spring内存马的代码，只是将pom.xml中的com.sun.tools修改为本地的tools.jar位置
```
        <dependency>
            <groupId>com.sun</groupId>
            <artifactId>tools</artifactId>
            <version>1.8.0</version>
            <scope>system</scope>
            <systemPath>C:/Program Files/Java/jdk1.8.0_144/lib/tools.jar</systemPath>
        </dependency>
```

操作系统：windows10
java环境：1.8.0_144

编译成功后，使用该项目release中的agent.jar加载自己编译的Spring内存马模块，报错（但是可以正常加载该项目release中的Spring内存马模块）
```
root@15d91da87780:/# java -jar agent.jar 1 springMemShell2.jar
id ==> 1
jarName ==> springMemShell2.jar
password ==> stdout
Exception in thread "main" com.sun.tools.attach.AgentLoadException: Agent JAR not found or no Agent-Class attribute
	at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:117)
	at AgentMain.main(AgentMain.java:31)
```

以为是agent.jar的问题，所以考虑自己编译agent.jar，在编译的过程中会报`no main manifest attribute`的错误,，在pom.xml中添加如下配置可正常编译
```
    <build>
        <plugins>
            <plugin>
                <!-- Build an executable JAR -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
<!--                            <classpathPrefix>resouces/</classpathPrefix>-->
                            <mainClass>AgentMain</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>
```
编译成功后，运行也报错
```
root@15d91da87780:/# java -jar agent2.jar 
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/tools/attach/AttachNotSupportedException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.AttachNotSupportedException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```

java使用其他版本同样不行，修改不同jdk所带的tools.jar也不起作用，请问师傅是windows平台的问题吗，还是在编译的过程中我有哪些没注意到的点，望师傅解答！！

**Comment by ethushiroha** [comment]
对于您疑问的解答：
  - agent.jar 可以加载本项目release中的springmemshell.jar，而无法加载自己编译的jar。参考报错信息可能是由于编译方式出错。您可以将自己编译的jar包解压之后查看里面 `META-INF/MAINIFEST.MF` 文件，其中`Agent-Class`属性是否正确。
![image](https://user-images.githubusercontent.com/49514644/131941451-2bd479ec-87d5-4c20-ac58-e208f93e257e.png)

  - 您编译可能使用的是`mvn`，本项目使用的是idea的`build->build Artifacts->Build/Rebuild`，可能对编译产生了影响。使用`mvn` 编译时您需要再次制定`Agent-Class`属性，可以参考[这篇文章](https://www.cnblogs.com/rickiyang/p/11368932.html)的如下部分（请自行替换其中配置）。
  ```xml
  <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-jar-plugin</artifactId>
      <version>3.1.0</version>
      <configuration>
          <archive>
              <!--自动添加META-INF/MANIFEST.MF -->
              <manifest>
                  <addClasspath>true</addClasspath>
              </manifest>
              <manifestEntries>
                  <Premain-Class>com.rickiyang.learn.PreMainTraceAgent</Premain-Class>
                  <Agent-Class>com.rickiyang.learn.PreMainTraceAgent</Agent-Class>
                  <Can-Redefine-Classes>true</Can-Redefine-Classes>
                  <Can-Retransform-Classes>true</Can-Retransform-Classes>
              </manifestEntries>
          </archive>
      </configuration>
  </plugin>
  ```

   - 本项目使用的编译方法如下图
![image](https://user-images.githubusercontent.com/49514644/131940398-38a82d1b-f3b5-4507-b6cb-a6e554216a8e.png)
  - 对于您最后的报错信息，猜测可能是jdk版本过低，本项目使用的jdk 1.8.0_282，具体您可以在idea中搜索`com.sun.tools.attach.AttachNotSupportedException`这个类，若确实不存在则使用较高版本jdk（如和本项目相同的jdk）

**Comment by Dido1960** [comment]
* 谢谢师傅惠答，确实是编译方式的问题，在使用idea自带的build编译选项，或者在pom.xml中添加Agent-Class等属性的配置后，自己编译的springmemshell可以正常加载。
* 对于agent.jar的编译，通过build编译，在jdk_1.8.0_144下同样可以正常使用，不过使用更低版本如jdk1.6就不行了，其他jdk版本情况未知。
